// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT59VX5InR8Y35jIhoHoZfWIHM39o102w',
    appId: '1:890103873272:web:be7e08fff6b235879ec50d',
    messagingSenderId: '890103873272',
    projectId: 'iot2-37a8f',
    authDomain: 'iot2-37a8f.firebaseapp.com',
    databaseURL: 'https://iot2-37a8f-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-37a8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQE_Ri6UYAxgRyr_SOJ1Aydd01h5QYFg',
    appId: '1:890103873272:android:ec4a78c3801e29119ec50d',
    messagingSenderId: '890103873272',
    projectId: 'iot2-37a8f',
    databaseURL: 'https://iot2-37a8f-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-37a8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZMh6yEa0vu0CgQUEFyQ298jBSEnND04',
    appId: '1:890103873272:ios:02859a5b07e18adf9ec50d',
    messagingSenderId: '890103873272',
    projectId: 'iot2-37a8f',
    databaseURL: 'https://iot2-37a8f-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-37a8f.appspot.com',
    iosBundleId: 'com.example.techHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRZMh6yEa0vu0CgQUEFyQ298jBSEnND04',
    appId: '1:890103873272:ios:0a4b53d2b7f02ea59ec50d',
    messagingSenderId: '890103873272',
    projectId: 'iot2-37a8f',
    databaseURL: 'https://iot2-37a8f-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-37a8f.appspot.com',
    iosBundleId: 'com.example.techHouse.RunnerTests',
  );
}
